//! Emit `data_uses.rs` snapshot source.

use std::fs;
use std::path::Path;

use crate::{DataUseScanError, OpKind, ScanHit, TargetKind};

/// Write the include file consumed by valence-uf-app (and other hosts).
pub fn write_snapshot(out_dir: &Path, hits: &[ScanHit]) -> Result<(), DataUseScanError> {
    fs::create_dir_all(out_dir).map_err(|e| DataUseScanError::Io {
        path: out_dir.to_path_buf(),
        message: e.to_string(),
    })?;
    let dest = out_dir.join("data_uses.rs");
    let body = render_snapshot(hits);
    fs::write(&dest, body).map_err(|e| DataUseScanError::Io {
        path: dest,
        message: e.to_string(),
    })?;
    Ok(())
}

fn render_snapshot(hits: &[ScanHit]) -> String {
    let mut code = String::new();
    code.push_str("// @generated by uf-valence-data-use-scan — do not edit\n");
    code.push_str("// Included from host build.rs / SSR modules.\n\n");
    code.push_str("/// One declared data-use row from the build-time scan.\n");
    code.push_str("#[derive(Debug, Clone, PartialEq, Eq)]\n");
    code.push_str("pub struct DataUseEntry {\n");
    code.push_str("    pub purpose: &'static str,\n");
    code.push_str("    pub file: &'static str,\n");
    code.push_str("    pub line: u32,\n");
    code.push_str("    pub crate_name: &'static str,\n");
    code.push_str("    pub target: DataUseTarget,\n");
    code.push_str("    pub op: DataOp,\n");
    code.push_str("    pub method: &'static str,\n");
    code.push_str("}\n\n");
    code.push_str("/// Target classification for a declared use.\n");
    code.push_str("#[derive(Debug, Clone, PartialEq, Eq)]\n");
    code.push_str("pub enum DataUseTarget {\n");
    code.push_str("    Schema(&'static str),\n");
    code.push_str("    Trait(&'static str),\n");
    code.push_str("    Unscoped,\n");
    code.push_str("}\n\n");
    code.push_str("/// CRUD-shaped operation bucket for UI tabs.\n");
    code.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    code.push_str("pub enum DataOp {\n");
    code.push_str("    Read,\n");
    code.push_str("    Create,\n");
    code.push_str("    Update,\n");
    code.push_str("    Delete,\n");
    code.push_str("}\n\n");
    code.push_str("/// Static catalog of production data uses (tests excluded when configured).\n");
    code.push_str("pub static DATA_USES: &[DataUseEntry] = &[\n");
    for hit in hits {
        code.push_str("    DataUseEntry {\n");
        code.push_str(&format!(
            "        purpose: {},\n",
            escape_str_lit(&hit.purpose)
        ));
        code.push_str(&format!("        file: {},\n", escape_str_lit(&hit.file)));
        code.push_str(&format!("        line: {},\n", hit.line));
        code.push_str(&format!(
            "        crate_name: {},\n",
            escape_str_lit(&hit.crate_name)
        ));
        code.push_str(&format!(
            "        target: {},\n",
            render_target(&hit.target)
        ));
        code.push_str(&format!("        op: {},\n", render_op(hit.op)));
        code.push_str(&format!(
            "        method: {},\n",
            escape_str_lit(&hit.method)
        ));
        code.push_str("    },\n");
    }
    code.push_str("];\n");
    code
}

fn render_target(target: &TargetKind) -> String {
    match target {
        TargetKind::Schema(name) => format!("DataUseTarget::Schema({})", escape_str_lit(name)),
        TargetKind::Trait(name) => format!("DataUseTarget::Trait({})", escape_str_lit(name)),
        TargetKind::Unscoped => "DataUseTarget::Unscoped".to_string(),
    }
}

fn render_op(op: OpKind) -> String {
    match op {
        OpKind::Read => "DataOp::Read".into(),
        OpKind::Create => "DataOp::Create".into(),
        OpKind::Update => "DataOp::Update".into(),
        OpKind::Delete => "DataOp::Delete".into(),
    }
}

fn escape_str_lit(s: &str) -> String {
    // Prefer raw strings when the purpose contains quotes or backslashes.
    if s.contains('\\') || s.contains('"') || s.contains('\n') {
        // Find a `#` count that does not appear in the payload terminator.
        let mut hashes = 1;
        loop {
            let delim = format!("{}\"", "#".repeat(hashes));
            if !s.contains(&delim) {
                break;
            }
            hashes += 1;
        }
        let pounds = "#".repeat(hashes);
        format!("r{pounds}\"{s}\"{pounds}")
    } else {
        format!("\"{s}\"")
    }
}
